### ISSUE TITLE
Переезд на ЮKassa до 15 февряля 2021

### ISSUE THREAD

**Issue by igor-tv** [hiqdev/omnipay-yandex-kassa#9]
Есть планы по изменению репозитория в связи с трансформацией Яндекс Касса -> ЮKassa?

Просят внести изменения до 15 февряля.

Новый SDK:
https://github.com/yoomoney/yookassa-sdk-php

**Comment by igor-tv** [comment]
Сделал [форк](https://github.com/igor-tv/omnipay-yookassa) пакета. Мейнтейнеры, похоже, забросили проект.

**Comment by hiqsol** [comment]
:+1:
этот задеприкейтим
